FROM node:22-alpine AS build

ENV CI=true
ENV FORCE_COLOR=true
WORKDIR /app

COPY ./apps/frontend/package.json .

RUN corepack enable
RUN pnpm install

COPY ./apps/frontend .

RUN pnpm build



FROM nginx:alpine AS runner

WORKDIR /app

COPY apps/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist .

CMD ["nginx", "-g", "daemon off;"]
